version: '3'

services:
  
  user-service:
    build: ./user-service
    ports:
      - "8500"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8443:8443"
    links:
      - user-service
    environment:
      - USER_SERVICE_HOST=user-service:8500